apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-ci-log-migrator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-log-migrator.labels" . | indent 4 }}