apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "estafette-ci-log-migrator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-log-migrator.labels" . | indent 4 }}
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "estafette-ci-log-migrator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Chart.AppVersion }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        {{- end }}
        {{- range $key, $value := .Values.extraPodLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "estafette-ci-log-migrator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 16 }}
          image: "{{ .Values.image.repository }}:{{ template "estafette-ci-log-migrator.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraArgs }}
          args:
            {{- toYaml . | nindent 16 }}
          {{- end }}
          env:
            - name: "API_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "estafette-ci-log-migrator.fullname" . }}
                  key: apiKey
            - name: API_URL
              value: {{.Values.apiUrl}}
            {{- if .Values.jaeger.enable }}
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
              value: http://$(JAEGER_AGENT_HOST):5778/sampling
            - name: JAEGER_SAMPLER_TYPE
              value: {{.Values.jaeger.samplerType}}
            - name: JAEGER_SAMPLER_PARAM
              value: "{{.Values.jaeger.samplerParam}}"
            - name: JAEGER_SERVICE_NAME
              value: {{ include "estafette-ci-log-migrator.fullname" . }}
            {{- else }}
            - name: JAEGER_DISABLED
              value: 'true'
            {{- end }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
      terminationGracePeriodSeconds: 300
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}