{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estafette-ci-log-migrator.serviceAccountName" . }}
  labels:
{{ include "estafette-ci-log-migrator.labels" . | indent 4 }}
{{- end -}}
